name: Auto Commit

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Execute committer
        run: |
          npm install
          git config --global user.name "Jubili Karan"
          git config --global user.email "jubilikaran@gmail.com"
          node ${GITHUB_WORKSPACE}/index.js
          git push origin main
